"""Greenfield scaffolding templates for the onboarding engine.

These helpers produce the *content* written by :mod:`spine.work.onboarding.scaffold`
when bootstrapping a brand-new (greenfield) project.  The generated
``.spine/config.yaml`` mirrors :class:`spine.config.SpineConfig`'s default keys
(``checkpoint_path``/``artifact_path``/``queue_path``/``workspace_root``) so that
``SpineConfig.load()`` succeeds against the scaffolded directory without further
edits.

All content is deterministic given its inputs so that re-scaffolding produces a
byte-identical tree (idempotency requirement of the onboarding engine).
"""

from __future__ import annotations

import yaml

from spine.config import SpineConfig


def baseline_config_yaml(tech_stack: list[str]) -> str:
    """Render a baseline ``.spine/config.yaml`` for a greenfield project.

    The produced YAML carries the same default keys as :class:`SpineConfig`
    (``checkpoint_path``, ``artifact_path``, ``queue_path``, ``queue_backend``,
    ``work_type``) so that :meth:`SpineConfig.load` parses it cleanly.  The
    ``tech_stack`` is recorded as a comment header so a human (or slice3's
    synthesis step) can see what the project was seeded with without it
    affecting config parsing.

    The ``providers:`` section is emitted as an empty ``llm: []`` / ``embedding: []``
    pair followed by commented-out stubs.  The empty arrays keep the parsed config
    structurally valid (``SpineConfig._load_providers`` is happy) while the
    commented stubs give the user a concrete editing target.

    Args:
        tech_stack: Technologies the project is seeded with, e.g.
            ``["python", "langgraph"]``.  Used only for the comment header.

    Returns:
        A YAML document string ending with a trailing newline.
    """
    defaults = SpineConfig()
    spine_block: dict[str, object] = {
        "checkpoint_path": defaults.checkpoint_path,
        "artifact_path": defaults.artifact_path,
        "queue_backend": defaults.queue_backend,
        "queue_path": defaults.queue_path,
        # Leave workspace_root empty so SpineConfig auto-detects via the
        # upward .spine/ search — hardcoding an absolute path here would
        # break the tree when the project is moved or cloned elsewhere.
        "workspace_root": "",
        "work_type": defaults.work_type,
    }
    # The codebase-index MCP server ships as a hard dependency of spine
    # (see pyproject `mcp-codebase-index`), so its `mcp-codebase-index`
    # entry point is always on PATH alongside spine. Emit an active server
    # block so the RAG indexer's `mcp_codebase-index_list_files` discovery
    # and the researcher's structural query tools work out of the box —
    # without this, a freshly scaffolded project logs "tool not available"
    # on `spine index`. PROJECT_ROOT is auto-injected by
    # spine.mcp.client.get_mcp_tools from the active workspace_root, so it
    # is intentionally not set here.
    mcp_block: dict[str, object] = {
        "codebase-index": {
            "transport": "stdio",
            "command": "mcp-codebase-index",
            "args": [],
        }
    }
    body = yaml.safe_dump(
        {
            "spine": spine_block,
            "mcp_servers": mcp_block,
            "providers": {"llm": [], "embedding": []},
        },
        sort_keys=False,
        default_flow_style=False,
    )

    stack = ", ".join(tech_stack) if tech_stack else "(unspecified)"
    header = (
        "# SPINE configuration — generated by the onboarding scaffolder.\n"
        f"# Tech stack: {stack}\n"
        "# Add LLM/embedding providers under `providers:` before running work.\n"
    )
    return header + body + _provider_stub_comment()


def _provider_stub_comment() -> str:
    """Return commented-out provider examples appended after the YAML body.

    These are pure YAML comments (every line starts with ``#``) so the document
    parses identically with or without them.  The shapes mirror the production
    config: ``deepagents-model`` for LLMs and ``openai-embedding`` for
    embeddings.  A user uncomments one of each, fills in ``base_url``/``model``,
    and points ``api_key`` at the env var holding their credential.
    """
    return (
        "\n"
        "# ── Example providers ─────────────────────────────────────────────\n"
        "# Uncomment and edit one LLM entry and one embedding entry, then move\n"
        "# them under `providers.llm:` / `providers.embedding:` above.\n"
        "#\n"
        "# providers:\n"
        "#   llm:\n"
        "#   - name: openrouter-default\n"
        "#     type: deepagents-model\n"
        "#     model: openrouter:deepseek/deepseek-v4-pro\n"
        "#     api_key: ${OPENROUTER_API_KEY}\n"
        "#     enabled: true\n"
        "#     guided_decoding: false\n"
        "#   - name: local-vllm\n"
        "#     type: deepagents-model\n"
        "#     model: openai:Qwen3.6-35B-A3B\n"
        "#     base_url: http://localhost:8000/v1\n"
        "#     api_key: vllm\n"
        "#     enabled: false\n"
        "#   embedding:\n"
        "#   - name: local-embeddings\n"
        "#     type: openai-embedding\n"
        "#     model: Qwen3-Embedding-8B-GGUF\n"
        "#     base_url: http://localhost:8010/v1\n"
        "#     api_key: vllm\n"
        "#\n"
        "# After editing, run `spine index` to build the RAG vector index,\n"
        "# then `spine run \"your task description\"`.\n"
    )


def _gitkeep_seed() -> str:
    """Content for a ``.gitkeep`` placeholder keeping an empty dir in git."""
    return ""


def default_dir_layout() -> dict[str, str]:
    """Return the greenfield directory/file layout to scaffold.

    Maps a repo-relative path to the seed content written there.  Directory
    placeholders are seeded with a ``.gitkeep`` file (empty content) so that
    otherwise-empty directories are tracked by git.  ``.spine/config.yaml`` is
    intentionally *omitted* here — it is rendered separately via
    :func:`baseline_config_yaml` because its content depends on the caller's
    ``tech_stack``.

    Returns:
        A mapping of repo-relative file path -> file content.  Every key is a
        file path (not a bare directory) so the scaffolder can write it
        directly; ``mkdir`` of parents is handled by the writer.
    """
    return {
        ".spine/skills/.gitkeep": _gitkeep_seed(),
        ".spine/artifacts/.gitkeep": _gitkeep_seed(),
        "src/.gitkeep": _gitkeep_seed(),
        "tests/.gitkeep": _gitkeep_seed(),
    }
