"""create work_entries table

Revision ID: c69967ea0727
Revises: 
Create Date: 2026-05-10 23:47:26.815081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c69967ea0727'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'timestamp', name='uq_work_entry_thread_ts')
    )
    op.create_index(op.f('ix_work_entries_thread_id'), 'work_entries', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_entries_thread_id'), table_name='work_entries')
    op.drop_table('work_entries')
    # ### end Alembic commands ###
